# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
permissions:
    contents: read

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        env:
            CC_TEST_REPORTER_ID: 3a5853627354f7cd705f3d9dc81fb83028c8a901a950a3d0d38a090776f8c5ce
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                node-version-file: '.nvmrc'
            - run: npm i
            - run: npm t
